lu crud incidentes
brasil-chile-connection/minguard-be pull request #10
Opened 2024-10-29 14:52 UTC by luanaFOliveira

- **created get urgency and initial configurations for incidents**
- **created register, update and delete functions for incidents**
- **fix register function and created update and delete function for incident**

2024-10-31 00:58 UTC, robertomahl requested changes

2024-10-31 00:58 UTC, robertomahl commented on src/main/java/com/minguard/controller/IncidentController.java
> +    @PreAuthorize("hasAuthority('ADMIN')")
Acho que esse vai ser usado pelo app também

2024-10-31 00:58 UTC, robertomahl commented on src/main/java/com/minguard/controller/IncidentController.java
> +    @PreAuthorize("hasAuthority('ADMIN')")
Acho que esse vai ser usado pelo app também
Se for pra listagem, podemos pensar se compensa retornar todos os dados de todos os incidentes ou alguns dados principais e, ao clicar em cima, buscar todos os dados por id. Se forem poucos incidentes talvez a diferença não seja tão significativa

2024-10-31 00:58 UTC, robertomahl commented on src/main/java/com/minguard/controller/IncidentController.java
> +    @PreAuthorize("hasAuthority('ADMIN')")
Acho que esse vai ser usado pelo app também

2024-10-31 00:58 UTC, robertomahl commented on src/main/java/com/minguard/controller/UrgencyController.java
> +    @PostMapping("/register")
Provavelmente deveria ser limitado ao administrador

2024-10-31 00:58 UTC, robertomahl commented on src/main/java/com/minguard/dto/incident/RegisterIncidentRequest.java
> +    @NotNull(message = "reporterId" + ValidationMessage.MUST_BE_SPECIFIED)
Talvez devessemos pegar o id do usuário logado, para evitar de permitir que se cadastre no nome de outra pessoa. Se for assim, removeríamos o id daqui

2024-10-31 00:58 UTC, robertomahl commented on src/main/java/com/minguard/util/Urgencys.java
> +public enum Urgencys {
Se tivermos as urgências cadastráveis, acho que não fica muito viável termos enum com algumas delas. Ao não ser que definamos que essas não poderão ser excluídas

2024-10-31 01:00 UTC, luanaFOliveira commented on src/main/java/com/minguard/util/Urgencys.java
> +public enum Urgencys {
ops esse esqueci de deletar soh o arquivo

2024-11-01 13:26 UTC, luanaFOliveira commented on src/main/java/com/minguard/controller/UrgencyController.java
> +    @PostMapping("/register")
o register?

2024-11-03 17:02 UTC, robertomahl approved these changes

2024-11-03 17:03 UTC, merged